config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :exercises_and_code do
      resources :students, only: :index, defaults: {format: :json}
    end
  end
  namespace :exercises_and_code do
    resources :students
  end

  root 'welcome#index'
end

app/models/student.rb
class Student
  include ActiveModel::Model

  attr_accessor :id, :name, :email, :street_number, :city, :zip_code, :country

  validates :name, presence: true, length: {maximum: 100}
  validates :email, presence: true, length: {maximum: 100}
  validates :street_number, presence: true, length: {maximum: 100}
  validates :city, presence: true, length: {maximum: 100}
  validates :zip_code, presence: true, length: {maximum: 100}
  validates :country, presence: true, length: {maximum: 100}

  def attributes
    [:id, :name, :email, :street_number, :city, :zip_code, :country]
  end

  def save
    return false unless valid?

    self.id = SecureRandom.hex

    true
  end

  def to_param
    id
  end
end

app/controllers/api/controller.rb
module Api
  class Controller < ActionController::Base

  end
end

app/controllers/api/exercises_and_code/students_controller.rb
require 'faker'

module Api
  module ExercisesAndCode
    class StudentsController < Api::Controller
      include StudentsArray

      before_action :set_allow_any_origin, only: :index
      before_action :set_allow_get_method, only: :index

      def index
        students = students(100)
        result = {description: "This is random data generated to support TCB (https://www.techcareerbooster.com) exercises",
                  type_of_results: 'students',
                  number_of_results: students.size,
                  results: students}

        respond_to do |format|
          format.xml {render xml: result}
          format.json {render json: result}
        end
      end

      private

      def set_allow_any_origin
        response.set_header('Access-Control-Allow-Origin', '*')
      end

      def set_allow_get_method
        response.set_header('Access-Control-Allow-Methods', 'GET')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/students_array.rb
require 'faker'

module StudentsArray
  extend ActiveSupport::Concern

  def students(number_of_students)
    Array.new(number_of_students) do
        {id: SecureRandom.hex,
         name: Faker::Name.name,
         email: Faker::Internet.email,
         address: {street_number: Faker::Address.street_address,
                   city: Faker::Address.city,
                   zip_code: Faker::Address.zip_code,
                   country: Faker::Address.country}
        }
    end
  end
end

app/controllers/exercises_and_code/students_controller.rb
module ExercisesAndCode
  class StudentsController < ApplicationController
    include StudentsArray

    def index
      # The problem with this is that we cannot do pagination because on every request, we get different
      # set of data. Can we use some cache?
      #
      # So, if the request does not contain "page" param, we create a new set and we save to the cache.
      # If the request contains "page" param, we read from the cache
      cache_key = 'students'

      if request.referer == root_url
        Rails.cache.delete(cache_key)
      end

      students = Rails.cache.fetch(cache_key) do
        populate_students
      end
      @students_with_pagination = Kaminari.paginate_array(students).page(params[:page].presence || 1).per(10)
    end

    def new
      @student = Student.new
    end

    def create
      @student = Student.new(student_params)
      if @student.save
        flash[:success] = 'Right! Student has been registered'
        redirect_to edit_exercises_and_code_student_path({id: @student.id, student: student_params})
      else
        flash.now[:error] = 'Please, correct the errors below'
        render :new
      end
    end

    def edit
      @student = Student.new({id: params[:id]}.merge(student_params))
    end

    def update
      @student = Student.new({id: params[:id]}.merge(student_params))
      if @student.save
        flash[:success] = 'Right! Student has been updated'
        redirect_to edit_exercises_and_code_student_path({id: @student.id, student: student_params})
      else
        flash.now[:error] = 'Please, correct the errors below'
        render :edit
      end
    end

    private

    def populate_students
      students(100)
    end

    def student_params
      params.require(:student).permit(:name, :email, :street_number, :city, :zip_code, :country)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def paginate(objects, options = {})
    options.reverse_merge!(theme: 'twitter-bootstrap-3')

    super
  end

  def bootstrap_class_for(flash_type)
    flash_type = flash_type.to_sym
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/views/exercises_and_code/students/_form.html.haml
= f.input :name, autofocus: true, required: true
= f.input :email, required: true
%fieldset
  %legend Address
  = f.input :street_number, required: true
  = f.input :city, required: true
  = f.input :zip_code, required: true
  = f.input :country, required: true

app/views/exercises_and_code/students/edit.html.haml
%h1 Student Edit Form

= simple_form_for @student, url: exercises_and_code_student_path(@student)  , html: {class: 'form-horizontal', method: :put} do |f|
  = f.input :id, disabled: true, readonly: true
  = render partial: 'exercises_and_code/students/form', locals: {f: f}
  = f.submit 'Update Student', class: 'btn btn-primary btn-lg'

app/views/exercises_and_code/students/index.html.haml
%h1 Students
- if @students_with_pagination.count

  = paginate @students_with_pagination

  %table.table.table-striped.table-bordered.table-hover.table-condensed
    %thead
      %tr
        %th ID
        %th Name
        %th Email
        %th{colspan: 4} Address
    %tbody
      - @students_with_pagination.each do |student|
        %tr
          %td= student[:id]
          %td= student[:name]
          %td= student[:email]
          %td= student[:address][:street_number]
          %td= student[:address][:city]
          %td= student[:address][:zip_code]
          %td= student[:address][:country]

app/views/exercises_and_code/students/new.html.haml
%h1 Student Registration Form

= simple_form_for @student, url: exercises_and_code_students_path, html: {class: 'form-horizontal'} do |f|
  = render partial: 'exercises_and_code/students/form', locals: {f: f}
  = f.submit class: 'btn btn-primary btn-lg'

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  .alert.fade.in{class: bootstrap_class_for(type)}
    %button.close{data: {dismiss: 'alert'}}×
    = message

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#navbar', aria: {expanded: 'false', controls: 'navbar'}}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Fake Data', root_path, class: 'navbar-brand'

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav

app/views/layouts/application.html.haml
!!!
%html{lang: :en}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: 'description', content: 'Free API with fake data that you can use with your own Web applications. It returns data in JSON and XML. Also, it has HTML tables with pagination.'}
    %title FakeData API - Tech Career Booster
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render partial: 'layouts/navbar'

    .container

      = render partial: 'layouts/flash'

      = yield

      %footer
        = link_to 'Panagiotis Matsinopoulos', 'https://www.matsinopoulos.gr'

app/views/welcome/index.html.haml
%h1 Endpoints

%ul
  %li
    Students
    %ol
      %li
        = link_to 'New Student', new_exercises_and_code_student_path
        &nbsp;
        = link_to 'Students List', exercises_and_code_students_path
        &nbsp;
        = link_to 'JSON', api_exercises_and_code_students_path(format: :json)
        &nbsp;
        = link_to 'XML', api_exercises_and_code_students_path(format: :xml)